spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qna
    username: bonojuno
    password: thisisTESTpw!#%&
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    open-in-view: false
  sql.init.mode: always
  #sql:
    #init:
      #data-locations: classpath*:db/h2/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "${OAUTH2_CLIENT_ID}"
            clientSecret: "${OAUTH2_CLIENT_PW}"
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  servlet:
    encoding:
      force-response: true
